### ISSUE TITLE
Gap between Cards in CardListView

### ISSUE THREAD

**Issue by daidai123** [gabrielemariotti/cardslib#157]
I want to remove space between cards in cardlistview. I am try to using cardslistview.setDivideHight(0), but it still contains space between cards. Can you instruct me what is the correct way to get ride off the space between cards?

**Comment by h4ck3rviv3k** [comment]
@gabrielemariotti Thanks for this trick but still there is divider is showing between cards, could you please let me know how we can remove that too. Thanks

**Comment by VishalSheth4** [comment]
<android.support.v7.widget.CardView
        android:id="@+id/card_view"
        android:layout_width="fill_parent"
        android:layout_height="100dp"
        android:layout_gravity="center"
        card_view:cardPreventCornerOverlap="false"
        card_view:cardElevation="0dp"
        card_view:cardMaxElevation="0dp">

**Comment by akibraza91** [comment]
its not working for me
