### ISSUE TITLE
Undo call doesn't work

### ISSUE THREAD

**Issue by ranchalp** [gabrielemariotti/cardslib#204]
Hi, I'm using your library and I have an issue when I want to customize calls to undo, what happens is that I can't control it because if I use the method Card.setOnUndoSwipeListListener the undo call doesn't do anything, not even execute the code defined here.

**Comment by leijdekkers** [comment]
Hi, I have the same issue. I have set the following listeners on my card and 2 listeners work as expected but not the setOnUndoSwipeListListener. I press the Undo button on the snackbar but the onUndoSwipe is never called. Any idea why? 

PS. I use this undo layout 
<include layout="@layout/list_card_undo_materialmobile_message"/>

However I noticed that when i tap the Undo text that the background area is wrapped around the Undo word and not as in the example the full hight of the snackbar. Not sure what is happening here...

# 

 card.setOnSwipeListener(new Card.OnSwipeListener() {
            @Override
            public void onSwipe(Card card)
            {
                Log.e(Constants.TAG, "onSwipe()");
            }
        });

```
    card.setOnUndoSwipeListListener(new Card.OnUndoSwipeListListener() {
        @Override
        public void onUndoSwipe(Card card)
        {
            Log.e(Constants.TAG, "onUndoSwipe()");
        }
    });

    card.setOnUndoHideSwipeListListener(new Card.OnUndoHideSwipeListListener() {
        @Override
        public void onUndoHideSwipe(Card card)
        {
            Log.e(Constants.TAG, "onUndoHideSwipe()");
        }
    });
```
