### ISSUE TITLE
Error on list and expandable card

### ISSUE THREAD

**Issue by BradleyRL** [gabrielemariotti/cardslib#23]
I was trying to implement this but everytime I've clicked the button to expand I got this error 

11-06 16:10:05.210: E/AndroidRuntime(646): FATAL EXCEPTION: main
11-06 16:10:05.210: E/AndroidRuntime(646): java.lang.NoSuchMethodError: android.view.View.setHasTransientState
11-06 16:10:05.210: E/AndroidRuntime(646):  at it.gmariotti.cardslib.library.view.CardListView$1.onPreDraw(CardListView.java:323)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:590)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1596)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2418)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.os.Looper.loop(Looper.java:137)
11-06 16:10:05.210: E/AndroidRuntime(646):  at android.app.ActivityThread.main(ActivityThread.java:4340)
11-06 16:10:05.210: E/AndroidRuntime(646):  at java.lang.reflect.Method.invokeNative(Native Method)
11-06 16:10:05.210: E/AndroidRuntime(646):  at java.lang.reflect.Method.invoke(Method.java:511)
11-06 16:10:05.210: E/AndroidRuntime(646):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
11-06 16:10:05.210: E/AndroidRuntime(646):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
11-06 16:10:05.210: E/AndroidRuntime(646):  at dalvik.system.NativeStart.main(Native Method)

I though i was doing something wrong but I've just tested the demo and it crashes too

**Comment by chiiiky14** [comment]
Thanks. It really works !
