### ISSUE TITLE
setupInnerViewElements on Scroll

### ISSUE THREAD

**Issue by BradleyRL** [gabrielemariotti/cardslib#28]
I'm having some trouble and i think its caused because whenever I scroll on the view the method setupInnerViewElements get called again everytime for every card

My example is I have a bunch of cards with seekbars and a textview to show the value of it, when i create the cards Ive send them the max and initial progress for it and it displays ok, but when i start scrolling the texview start showing random values without a seekbar change.

Any reason of why are you calling  setupInnerViewElements  when you scroll through the view everytime ?

**Comment by uzumakinaruto123** [comment]
I have a similar issue , can you help with this https://github.com/gabrielemariotti/cardslib/issues/545
thanks
