### ISSUE TITLE
Programmatically Insert Views into CardExpand layout

### ISSUE THREAD

**Issue by ScottCooper92** [gabrielemariotti/cardslib#308]
Hi,

I have a CustomExpandCard which I give a layout. What I would like to do is insert views into this layout at runtime. 

I have tried using Framelayouts and inserting views in the setupInnerViewElements method which doesn't work, and I've also tried a LinearLayout and addView( view ) which also doesn't work.

**Comment by kyrogue** [comment]
Hey, have you found a solution? im having the same problem as you
