### ISSUE TITLE
CardListView with cards with EditText

### ISSUE THREAD

**Issue by ben04** [gabrielemariotti/cardslib#322]
Hey,

I just built a CardListView with several cards with a custom layout. This time the layout includes an EditText.

The problem is, when the user clicks into the EditText, the keyboard appears, but right after that the focus on the EditText disappears and if I try to type, nothing happens.
I guess this happens because of the reloading of the list after the keyboard appears over a part of it. Though I can't find a way to solve that and be able to use the keyboard...can you help me here?

Greetz Ben

**Comment by chandruscm** [comment]
Bumped into the same issue, your solution works like a charm @ben04 ! Thank you :)
