### ISSUE TITLE
How to set cards inside a cardlist clickable ?

### ISSUE THREAD

**Issue by crazyhitty** [gabrielemariotti/cardslib#338]
I am actually new in android development, so is it possible to use something like setOnItemClickListener  for the cardlist like a simple list view.

```
        for(int i=0;i<6;i++) {
        //Create a Card
        Card card = new Card(getActivity());

        //Create a CardHeader
        CardHeader cardHeader = new CardHeader(getActivity());

        //Add Header to card
        cardHeader.setTitle(cardTitle[i]);
        card.addCardHeader(cardHeader);

        //Add thumbnails to the card
        CardThumbnail thumb = new CardThumbnail(getActivity());
        thumb.setDrawableResource(listImages[i]);
        card.addCardThumbnail(thumb);

        cards.add(card);

        //Enable card swipe
        //card.setSwipeable(true);
        //card.setId("card0"+i);
        }
        CardArrayAdapter cardArrayAdapter=new CardArrayAdapter(getActivity(), cards);
        CardListView cardListView= (CardListView) getActivity().findViewById(R.id.myList);
        if(cardListView!=null)
        {
            cardListView.setAdapter(cardArrayAdapter);
        }
        /*cardListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            Toast.makeText(getActivity(), cardTitle[position], Toast.LENGTH_SHORT).show();
        }
        });
        */
```

**Comment by Kondra007** [comment]
for (int i = 0; i<10; i++) {
            //Create a Card
            Card card = new Card(getApplicationContext());
            //Create a CardHeader
            CardHeader header = new CardHeader(getApplicationContext());
            header.setButtonExpandVisible(true);
            header.setTitle("Header #" + i);

            CustomCardExpand exp = new CustomCardExpand(getApplicationContext());
            card.addCardHeader(header);

            card.setOnClickListener(new Card.OnCardClickListener() {
                @Override
                public void onClick(Card card, View view) {
                    Toast.makeText(MainActivity.this, card.getId() + " " + card.getTitle() + " ", Toast.LENGTH_SHORT).show();
                }
            });

            cards.add(card);
        }

And on card click I get "null null" for every card :(

**Comment by gabrielemariotti** [comment]
DId you set the id and the title attributes in the card ?
