### ISSUE TITLE
CardRecyclerView with MaterialLargeImageCard

### ISSUE THREAD

**Issue by andreac** [gabrielemariotti/cardslib#391]
Hi, I want to use CardRecyclerView wirh a material card, using the provided layout. It show the card, but not the content, can you help me?
```
public class TripContents extends Activity{
    CardRecyclerView mRecyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_trip_contents);
//        recList = (RecyclerView) findViewById(R.id.cardList);
//        recList.setHasFixedSize(true);
//        LinearLayoutManager llm = new LinearLayoutManager(this);
//        llm.setOrientation(LinearLayoutManager.VERTICAL);
//        recList.setLayoutManager(llm);




        final ArrayList<Card> cards = new ArrayList<Card>();

        final CardArrayRecyclerViewAdapter mCardArrayAdapter = new CardArrayRecyclerViewAdapter(this, cards);
        mRecyclerView = (CardRecyclerView) findViewById(R.id.cardList);
        mRecyclerView.setHasFixedSize(false);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        if (mRecyclerView != null) {
            mRecyclerView.setAdapter(mCardArrayAdapter);
        }


        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.attachToRecyclerView(mRecyclerView);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(TripContents.this, AddTripContent.class);
                TripContents.this.startActivity(i);
            }
        });


        ParseQuery<Trip_Content> query = ParseQuery.getQuery(Trip_Content.class);
        query.whereEqualTo("user", ParseUser.getCurrentUser());
        query.findInBackground(new FindCallback<Trip_Content>() {
            @Override
            public void done(List<Trip_Content> results, ParseException e) {
                if (results.isEmpty()){

                    MaterialLargeImageCard c = new MaterialLargeImageCard(ApplicationContext.getAppContext());
                    c.setTitle("test");
                    c.setSubTitle("don't have contents");


                    cards.add(c);
                    mCardArrayAdapter.notifyDataSetChanged();

                }else{
                    //add trip_content
                }


            }

        });


    }
}

```
And this is the layout

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    xmlns:card="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin">
    <!--<android.support.v7.widget.RecyclerView
        android:id="@+id/cardList"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />-->
    <it.gmariotti.cardslib.library.recyclerview.view.CardRecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        card:card_layout_resourceID="@layout/native_material_largeimage_text_card"
        style="@style/card_external"
        android:id="@+id/cardList"/>

    <com.melnykov.fab.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="bottom"
        android:layout_margin="16dp"
        android:src="@drawable/ic_add_white_24dp"
        fab:fab_colorNormal="@color/myAccentColor"
        fab:fab_colorPressed="@color/bkg_card"
        android:layout_alignParentBottom="true"
        android:layout_alignRight="@+id/cardList"
        android:layout_alignEnd="@+id/cardList" />
</RelativeLayout>

```

And what it show
![screenshot_2015-01-06-10-58-04](https://cloud.githubusercontent.com/assets/180125/5627049/c167ebc2-9593-11e4-9b88-727696dfc9ec.png)

**Comment by andreac** [comment]
Finally i solved implementing my personal Material card and it works fine! :)

**Comment by sumitsahoo** [comment]
I am having the same problem. Can you please explain how you fixed it ?

**Comment by AkshayChordiya** [comment]
@andreac 
I too need it

**Comment by gabrielemariotti** [comment]
Nothing different form other cards, just use a layout with the native_material_largeimage_text_card.

You can find an example here:
https://github.com/gabrielemariotti/cardslib/blob/dev/demo/stock/src/main/java/it/gmariotti/cardslib/demo/fragment/nativeview/NativeRecyclerViewMaterialCardFragment.java

@andreac It is better to use the the builder instead of the normal constructor.
Also you should call the card.build();

There is a bug that I am investigating #361

**Comment by sumitsahoo** [comment]
@gabrielemariotti I have updated the xml file as 

material_card.xml :

<it.gmariotti.cardslib.library.view.CardViewNative
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card="http://schemas.android.com/apk/res-auto"
    android:id="@+id/list_cardId"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    style="@style/native_recyclerview_card.base"
    card:card_layout_resourceID="@layout/native_material_largeimage_text_card"/>

In layout xml :

<it.gmariotti.cardslib.library.recyclerview.view.CardRecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/myCardList"
        card:list_card_layout_resourceID="@layout/material_card" />

Still I am getting the basic cards instead of material ones. Anything missing  ?
Thanks a lot for this library.

**Comment by sumitsahoo** [comment]
Finally solved it. The problem was in xml declaration. By mistake I copied it wrong. xmlns:card="http://schemas.android.com/apk/res-auto"

Thanks a lot for the help. This library just rocks :)

**Comment by sumitsahoo** [comment]
Just a quick question, if I want to style the cards differently should I use this inside for loop ?

CardViewNative cardViewNative = (CardViewNative)     findViewById(getResources().getIdentifier("list_cardId"+i, "id", getPackageName()));
cardViewNative.setCard(card);

**Comment by gabrielemariotti** [comment]
No you can't do it in a list.
What would you achieve ?


Il giorno Thu Jan 15 2015 at 10:34:00 sumitsahoo <notifications@github.com>
ha scritto:

**Comment by sumitsahoo** [comment]
I was trying to have multi type cards in RecyclerView. So I thought maybe it can be done grammatically by changing the layout of CardViewNative. Any ideas on how to achieve this ?

**Comment by gabrielemariotti** [comment]
This feature is not supported yet.

Il giorno Thu Jan 15 2015 at 11:32:59 sumitsahoo <notifications@github.com>
ha scritto:

**Comment by sumitsahoo** [comment]
Ok ... no problem. Thanks. Well the multi layout will be great in future :)

**Comment by JoachimR** [comment]
for some reason I experienced the same problem. When I renamend my id in the carditem differently than the whole layout it works. :

carditem.xml
```
<it.gmariotti.cardslib.library.view.CardViewNative
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card="http://schemas.android.com/apk/res-auto"
     android:id="@+id/list_cardId" <!---------------- if this was "@+id/carditem" nothing would show up ?!

    android:layout_width="match_parent"
    android:layout_height="wrap_content"


    style="@style/native_recyclerview_card.base"
    card:card_layout_resourceID="@layout/native_material_largeimage_text_card"/>
```
