### ISSUE TITLE
Increase touch area of card popup button

### ISSUE THREAD

**Issue by vit001** [gabrielemariotti/cardslib#394]
What is the recommended way to increase the touch area of a card's popup button (three vertical dots)? Thank you.

**Comment by gabrielemariotti** [comment]
You should change the built-in layout of the header.
You are the first that write about an issue of the touch area. Is it small? Are you using the cardNative?

**Comment by vit001** [comment]
OK, I will try. Yes, it is too small for me. I do use cardNative. My issue is that my card itself is clickable, and with the popup touch area being small, often times my popup click is interpreted as a card click. Thank you.
