### ISSUE TITLE
I need CardGridView with Footer view 

### ISSUE THREAD

**Issue by KiminRyu** [gabrielemariotti/cardslib#395]
Hi.
First of all, I appreciate that your library is a very proper for my company's product.

My problem is...
I need CardGridView with Footer view but your library doesn't support it.
Is there any solution with this problem? and you have any plan to support it?

**Comment by gabrielemariotti** [comment]
The android GridView doesn't support a Footer view.
I am planning something with the RecyclerView, not the GridView
