### ISSUE TITLE
Setting CardHeader Title text color dynamically (programmatically)

### ISSUE THREAD

**Issue by kamisrini** [gabrielemariotti/cardslib#396]
Hello,

I am not sure, this is an issue or beginner's confusion.  

In my project, i am trying to set color of title for card's header, but it seems to be getting NullPointerException.

I tried below, everything works as expected, but setting color on header title fails.

    Card card = new Card(getContext());  

    CardHeader header = new CardHeader(this);
    header.setTitle(evaluationWords[i]);
   
    //the following line, gives me null
    TextView headerTitle = (TextView)this.findViewById(R.id.card_main_inner_simple_title);
    headerTitle.setTextColor(getResources().getColor(R.color.noaccentlightgray));

    card.addCardHeader(header);

When I debug it fails after the following line with NullPointerException.
    TextView headerTitle = (TextView)this.findViewById(R.id.card_main_inner_simple_title);'

I have also tried 
    TextView headerTitle = (TextView)this.findViewById(R.id.card_header_inner_simple_title);, but no luck.

If I am doing it wrong, I will appreciate any guidance. 

Thanks in advance.
Srini

Here is whole class, just in case.

public class CardListActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_card_list);

        ArrayList<Card> cards = new ArrayList<Card>();

        for (int i = 0; i < 5; i++) {
            // Create a Card
            NoAccentCard card = new NoAccentCard(this, R.layout.row_card);

            CardHeader header = new CardHeader(this);
            header.setTitle(evaluationWords[i]);
			TextView headerTitle = (TextView)this.findViewById(R.id.card_main_inner_simple_title);
            headerTitle.setTextColor(getResources().getColor(R.color.noaccentlightgray));

            card.addCardHeader(header);

            card.setId(lowercaseFirstLetter(evaluationWords[i]));

            //add cards to arraylist
            cards.add(card);
        }
        //create adapter
        CardArrayAdapter mCardArrayAdapter = new CardArrayAdapter(this, cards);

        //set adapter on the list
        CardListView listView = (CardListView) this.findViewById(R.id.myList); 
        if (listView != null) {
            listView.setAdapter(mCardArrayAdapter);
        }

    }

}

**Comment by gabrielemariotti** [comment]
It is wrong.
You can do it only inside the setupInnerViewElements method.

```java
public class MyHeader extends CardHeader {

        public MyHeader(Context context) {
            super(context);
        }

        @Override
        public void setupInnerViewElements(ViewGroup parent, View view) {

            if (view!=null){
                TextView t1 = (TextView) view.findViewById(card_main_inner_simple_title);
                if (t1!=null)
                       //
            }
        }
    }
```

Also you can change the color using the style:
https://github.com/gabrielemariotti/cardslib/blob/master/doc/HEADER.md#style
```xml
<color name="card_text_color_header">#990066</color>
```

**Comment by kamisrini** [comment]
Thanks Gabriel, I will try this.  The second option works for me, but I have to change it code, as color is dependent on associated logic.

**Comment by kamisrini** [comment]
Hi Gabriel,

This worked perfectly, thanks for help.

Keep up the great work. Cheers!

Srini
