### ISSUE TITLE
Death link at changelog (Learn how to migrate your cards)

### ISSUE THREAD

**Issue by acacha** [gabrielemariotti/cardslib#411]
At,

https://github.com/gabrielemariotti/cardslib/blob/master/CHANGELOG.md

The link to Learn how to migrate your cards.

I was looking for CardViewNative differences vs CardView wich one you recommend and some background info to better understanding of cardslib.

Thanks,

**Comment by acacha** [comment]
FYI I've found https://github.com/gabrielemariotti/cardslib/blob/master/doc/MIGRATE.md

**Comment by gabrielemariotti** [comment]
Thanks!
