### ISSUE TITLE
How to get card internal element and set onClick method?

### ISSUE THREAD

**Issue by willowcheng** [gabrielemariotti/cardslib#421]
I've known how to set click on a single card. While I use the customize layout, I want to use `setOnClickListener()` for a button inside the card.

I've tried

``` java
card.getCardView().getInternalThumbnailLayout().findViewById(R.id.add_new_food).setOnClickListener
```

or

``` java
card.getInnerView(getActivity(), null).findViewById(R.id.add_new_food).setOnClickListener
```

but get NullPointer error.

**Comment by kamisrini** [comment]
In  setupInnerViewElements define Handler, as below

 @Override
    public void setupInnerViewElements(ViewGroup parent, View view) {
        super.setupInnerViewElements(parent, view);

View.OnClickListener playHandler = new View.OnClickListener() {
            public void onClick(View v) {

               play();

            }
        };

And then attach hanlder to clicklistener

      //Retrieve play button
        play = (ImageView) parent.findViewById(R.id.play);
        if (play != null)
            play.setOnClickListener(playHandler);
}
