### ISSUE TITLE
when using the cardslib appear oom

### ISSUE THREAD

**Issue by Smalinuxer** [gabrielemariotti/cardslib#422]
I instance of lots of different type of cards which is subclass of Card . I use a list to collect them. 
every time , the listview being instance . I request to server and server responce me json to instance every type of cards . after that I using the CardArrayAdapter to adapter view . 

when the listview slide to bottom , I will request again and add to adapter . 
but I found that : I cann't unlimited add cards to adapter . 
It appear oom . because I add so many . 
how can I fix it ?

My English is bad :)

**Comment by Smalinuxer** [comment]
I don't know whether it caused by the without RecycleBin to recycle the view or just because build too much card(view) in the memory.
if it is the latter , it will lead the view problem which means we can't unlimited wheel down(unlimited cards in the listview) 

:)

**Comment by jiaqizho** [comment]
sorry,
that time was too simple 
then i work out that the the problem that it appear by my uil bug
wtf?

thank you provider this amazing frame ~
