### ISSUE TITLE
Fail on build

### ISSUE THREAD

**Issue by grgr07** [gabrielemariotti/cardslib#423]
Hello,
first of all it great library, but I have huge issue to build it.
I just can't, it fail with 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 2

I use Android Studio 1.1, JDK 1.8, SDK 21, Windows 7 64bit. I did success compile on virtual machine with 32bit(but it too too slow)
Please help.
Gregory
I tried with dependency/compile from source. Unsuccessfully.

**Comment by gabrielemariotti** [comment]
Have you tried to use JDK 1.7 ?

**Comment by thatishemanth** [comment]
Even i tried with JDK 1.7 also problem not soved.
