### ISSUE TITLE
button inside card grid. How to retireve button on click? 

### ISSUE THREAD

**Issue by chihao12** [gabrielemariotti/cardslib#430]
I have a button inside my card. I need to pass the position of that card along with some data inside an arraylist to another activity. How can i get the button on Click? as well as the position of the card?

**Comment by JP1016** [comment]
did you get the solution?

**Comment by MJmichael** [comment]
yes,thanks

在 2015-10-25 22:56:26，"JP1016" notifications@github.com 写道：

did you get the solution?
