### ISSUE TITLE
MaterialLargeImageCard isn't showing Title and Subtitle

### ISSUE THREAD

**Issue by krupalshah** [gabrielemariotti/cardslib#433]
My java code is as following:
MaterialLargeImageCard card =
                MaterialLargeImageCard.with(mContext)
                        .setTitle(mTripModel.getTitle())
                        .setSubTitle("Trip To " + mTripModel.getDestination())
                        .useDrawableExternal(new MaterialLargeImageCard.DrawableExternal() {
                            @Override
                            public void setupInnerViewElements(ViewGroup parent, View viewImage) {
if (!mTripModel.getCoverphotourl().equals("")) {
                                    Picasso.with(mContext)
                                            .load(ServerHandler.API_URL + mTripModel.getCoverphotourl())
                                            .resize(600, 400)
                                            .centerCrop()
                                            .into((ImageView) viewImage);
                                }
                            }
                        })
                        .setupSupplementalActions(R.layout.categorized_trips_cardview_actions, arrayListActions)
.build();

and in xml:

 <it.gmariotti.cardslib.library.view.CardViewNative
        android:id="@+id/cardview_categorizedtrip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        card:card_layout_resourceID="@layout/native_material_largeimage_card"
        style="@style/card_external"
        />

I can't get title and subtitle under image. It seems like setTitle() and setSubtitle() isn't working.

**Comment by JP1016** [comment]
im having the same problem why subtitles and titles are not shown
