### ISSUE TITLE
How to use cardslib as an eclipse project? 

### ISSUE THREAD

**Issue by harveyslash** [gabrielemariotti/cardslib#435]
I want to use Cardslib as a library project in Eclipse. However , on importing the project library-core, i get many errors similar to this: 

appcompat_v7\res\values-v21\themes_base.xml:193: error: Error: No resource found that matches the given name: attr 'android:colorControlNormal'.

What do I do?

**Comment by gabrielemariotti** [comment]
Are you compiling with api21?

Il giorno lun 13 apr 2015 alle ore 13:09 harveyslash <
notifications@github.com> ha scritto:
