### ISSUE TITLE
Build failed upon adding in dependencies in android studio

### ISSUE THREAD

**Issue by SoumyadipAuddy** [gabrielemariotti/cardslib#444]
i just added your library in the gradle.build file when i got this error upon building the project. Plz help.

:app:processDebugResources
ERROR: In <declare-styleable> ForegroundLinearLayout, unable to find attribute android:foregroundInsidePadding
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\androidSdk64bit\adt-bundle-windows-x86_64-20140702\sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 1

the dependencies section look like this:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.android.support:support-v4:22.1.1'
    compile 'com.github.gabrielemariotti.cards:library:1.9.1'
}

**Comment by MrDarpan** [comment]
I have Same problem....

**Comment by Kinnonii** [comment]
+1

**Comment by Kinnonii** [comment]
Found the problem: SDK 22. Created a new issue.

**Comment by Kinnonii** [comment]
UPDATE: Solved (at least my case)
I was using build tools version 21.1.2 and had set the compile SDK and target SDK to API 22. That was the problem. Switching to API 21 worked perfectly, but, the best solution is to upgrade your build tools to 22.0.1, now it works perfectly with API 22 too.

**Comment by gabrielemariotti** [comment]
I've just update to 2.1.0.
It uses the last support libraries 22.1.1, and should solve any problem.

**Comment by niltmt** [comment]
I am having the same problem with aapt from all version of build tool when I try to set it up with gradle. FYI, I have tried build tool from v191 to v23 and non of them works!
