### ISSUE TITLE
Is there a pull down to refresh view in Listviewcard

### ISSUE THREAD

**Issue by lmouhib** [gabrielemariotti/cardslib#454]
I am wondering of there is the pull down to refresh feature to cardlistview?? I want to add as I am uploading data from a serve and need to update the list just with the pull down feature. Thanks!

**Comment by JGeraldoLima** [comment]
Hi, I don't use cardlistview but I was up to use v4 Swipe in both common ListView and RecyclerView. You just need to wrap your view in a android.support.v4.widget.SwipeRefreshLayout:

(The "android.support.v4.widget.SwipeRefreshLayout>" xml part does not appear here, I don't know why. So you have to complete after paste)

"<"android.support.v4.widget.SwipeRefreshLayout
                xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/swipe_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent" >

                <ListView
                    android:id="@+id/listView"
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent">
                </ListView>
</android.support.v4.widget.SwipeRefreshLayout>


And in java:

private SwipeRefreshLayout swipeLayout;

/** The on refresh listener. */
OnRefreshListener onRefreshListener = new OnRefreshListener() {

	@Override
	public void onRefresh() {

		new Handler().postDelayed(new Runnable() {

			@Override
			public void run() {
				swipeLayout.setRefreshing(false);
				//do your stuff
			}
		}, 2000);
	}
};


swipeLayout = (SwipeRefreshLayout) view
					.findViewById(R.id.swipe_container);
swipeLayout.setOnRefreshListener(onRefreshListener);
swipeLayout.setColorScheme(/*you can choose another colors*/ android.R.color.holo_blue_bright,
					android.R.color.holo_blue_light);

Hope it helps :)

**Comment by lmouhib** [comment]
Thanks, I'll try it!

**Comment by lmouhib** [comment]
@JGeraldoLima I tried the code and it kind of worked, however, the list doesn't get updated, the little circle just keep spinning, where could be the problem??

**Comment by JGeraldoLima** [comment]
Huh, it is just a implementation detail.. in my case, I start a service to download news. Once I get the news, the receiver takes the task of update the list. Could you paste the code inside of OnRefreshListener so I can check this out? You can see a simple example here: https://www.bignerdranch.com/blog/implementing-swipe-to-refresh/

**Comment by lmouhib** [comment]
@JGeraldoLima it was working fine, it was a UI issue, I just need to set SwipeRefreshLayout.setRefreshing to false! Thanks!

**Comment by JGeraldoLima** [comment]
Cool, you're welcome :) (You just had to pay attention to the code I've paste, I put this line on the first answer! :p)
