### ISSUE TITLE
ListView recycling problem

### ISSUE THREAD

**Issue by Maximus547** [gabrielemariotti/cardslib#462]
Hello,
Here's the code

 card.setOnClickListener(new Card.OnCardClickListener() {
            @Override
            public void onClick(Card card, View view) {
                card.doToogleExpand();
                TextView tv = (TextView) view.findViewById(R.id.card_inner_textView2);
                tv.setVisibility(View.GONE);
            }
        });

The problem is whenever I click on a card and its view is gone but when I scroll down see a few other cards have the same layout. I think that has to do with recycling listview. I am using your ListView and ListView adapter.
Thank you.

**Comment by 7va** [comment]
I have the same "bug" with edditable views on cards. Tryin' to extends CardDragDropArrayAdapter and @Override the getView() with all available methos like this: http://www.rogcg.com/blog/2013/03/12/recycling-views-listview

But it dosn't help.

**Comment by gabrielemariotti** [comment]
@Maximus547  @7va You can't do it in this way.

The list works with the adapter which reads the card value.
You have to change the value inside the card, not the ui.

Each card display the info based on the model and the `setupInnerViewElements` method.

When you scroll the list, the `ListView` call the `adapter.getView()` method which call the `setupInnerViewElements`.

You have to set a boolean inside that card, update the adapter (!), then provide a if inside your setupInnerViewElements method.

```java
     @Override
      public void setupInnerViewElements(ViewGroup parent, View view) {
            if (myBoolean){ 
               tv.setVisibility(View.GONE);
           } else {
              tv.setVisibility(View.VISIBLE);
          }
      }
```

**Comment by 7va** [comment]
@gabrielemariotti, Thank you for answer and big respect for this great lib, btw!
 What mean "set a boolean inside that card" ? Im not so long android developer, so sorry if that a noob qestion. 
Im tryin' to create list of cards based on Drag'n'Drop extra lib.  I need a edittext's and checkboxes on it. So when i set checkbox in first row is checked and scrolldown the list - i found random row is also checked. When i scroll back, the first row is unchecked for now, but random nearby row is. 
This (http://gmariotti.blogspot.ru/2013/06/tips-for-listview-view-recycling-use.html) solution don't get even result. And i totaly don't know what to do.

**Comment by gabrielemariotti** [comment]
@7va 
The boolean case is referred to @Maximus547.

In your case, you have to set the value (true/false) of checkboxs and the values of the editText inside the `Card`.

Something like;

```java
public class MyCard extends Card{
     
     boolean checked;
     String editTextString;
  
}
```

**Comment by 7va** [comment]
@gabrielemariotti 
Yeah, it's alive! Alive!!!!
Thank you very match!
