### ISSUE TITLE
Dynamically remove card from CardGrid via popup menu

### ISSUE THREAD

**Issue by dannybabbev** [gabrielemariotti/cardslib#474]
Hello,
Can you please suggest a way to dynamically remove card from my CardGridView via the popup menu, which is an anonymous inner class?

**Comment by gabrielemariotti** [comment]
You have to remove the card from the adapter and call the `notifydatasetchanged`

**Comment by dannybabbev** [comment]
Thanks for the fast reply, I managed to do it by deleting the card item from the ArrayList and then re adapting the data via a helper method. 
```java
private void adaptCardArray() {
        mCardArrayAdapter = new CardGridArrayAdapter(this, mCards);
        CardGridView gridView = (CardGridView) findViewById(R.id.myGrid);
        if (gridView != null) {
            gridView.setAdapter(mCardArrayAdapter);
        }
    }
```
I call this method every time an item is removed from the list. Is this better way, because if I only remove the card from the adapter, it stays in the array and I seek good performance?

**Comment by gabrielemariotti** [comment]
The better way is to remove the item from the adapter and notify the change.
You are creating a new adapter each time.

**Comment by dannybabbev** [comment]
I have an adapter field and setting it every time. Anyways, thanks for the replies. I will remove the item from the adapter first, as you said, and then from the list. 

PS: Cheers for the nice library! :)
