### ISSUE TITLE
Animate a card on click

### ISSUE THREAD

**Issue by dannybabbev** [gabrielemariotti/cardslib#475]
Hello,
Is there a way of applying a view animation on card on click, like the ones provided in AndroidViewAnimations library? I've tried to get the View from the current card with the getInnerView() method but an UnsupportedOperationException is thrown.

```java
java.lang.UnsupportedOperationException: addView(View) is not supported in AdapterView
```

**Comment by gabrielemariotti** [comment]
It depends by your code.

**Comment by dannybabbev** [comment]
I use AndroidViewAnimation-s library like this, where Techniques is whatever I choose and playOn() method, which requires a View:
```java
YoYo.with(Techniques.Tada)
    .playOn(findViewById(R.id.edit_area));
```
I try go get the view from the Card returned by the onClick() method, which requires Context and a ViewGroup. ViewGroup is my CardGridView in the layout:

```java
cardGen.setOnClickListener(new Card.OnCardClickListener() {
                @Override
                public void onClick(Card card, View view) {
          
                    //FIXME: Add animation
                    YoYo.with(Techniques.FlipOutX)
                    .playOn(card.getInnerView(getBaseContext() , (ViewGroup) findViewById(R.id.myGrid)));
                }
            });
            mCards.add(cardGen);
        } 
```

With this approach an UnsupportedOperationException is thrown. Maybe this is not the right way to handle this situation so i change my statement to get the card View from CardAdapter , statement looks like:

```java

mCardArrayAdapter.getView(getCardIndex(card) , /*covertView needed*/ , R.id.myGrid);

```

But I don't know how and from where to get convertView.

Any suggestions here?

**Comment by dannybabbev** [comment]
This issue was resolved by using the View in the onClick() methd... what a silly mistake.

```java
public void onClick(Card card, View view) {

                    //FIXME: Add animation
                    YoYo.with(Techniques.FlipOutX)
                    .playOn(view);
                }
```
