### ISSUE TITLE
Change title color to black (#000)

### ISSUE THREAD

**Issue by AkshayLaghate** [gabrielemariotti/cardslib#476]
I am using Material card with text, i want to change title color to black. I have seen the documents many times but can't figure out how to do it. Pls help me.

**Comment by gabrielemariotti** [comment]
If you are referring the title over the image:

```xml
<color name="card_thumbnail_image_text_over_textcolor">#FFF</color>
```

**Comment by AkshayLaghate** [comment]
Not over the image, the title and subtitle below the image.

**Comment by gabrielemariotti** [comment]
Here the layout used 
https://github.com/gabrielemariotti/cardslib/blob/master/library-cards/src/main/res/layout/native_material_largeimage_inner_base_main.xml

You can override the style `card.native.base_simple_title`.

Here the original value:
https://github.com/gabrielemariotti/cardslib/blob/master/library-core/src/main/res/values-v16/styles.xml#L64

I have to extract the color from this.
It would be easier to change the color :-/

**Comment by AkshayLaghate** [comment]
That worked. Thanks
