### ISSUE TITLE
Recycle GridCard

### ISSUE THREAD

**Issue by chamroeunbm** [gabrielemariotti/cardslib#482]
Hi,

Is there any way to recycle gridcard? Recycler here can only used with Listview?

Thanks;

**Comment by gabrielemariotti** [comment]
Currently there isn't a Layout implemented.

**Comment by chamroeunbm** [comment]
Thanks!

Can you give me some hint how to do that? I have 500+ grid cards.

**Comment by gabrielemariotti** [comment]
You should try what happens when you use the CardRecyclerView with a GridLayoutManager

**Comment by chamroeunbm** [comment]
Thanks;
