### ISSUE TITLE
CardExpand ViewToClickToExpand listener not added in RecyclerView

### ISSUE THREAD

**Issue by Dokuzov** [gabrielemariotti/cardslib#483]
ArrayList<Card> cards = new ArrayList<>();
        c = (CardView) findViewById(R.id.card);
        for (int i = 0; i < 20; i++) {
            ViewToClickToExpand viewToClickToExpand = ViewToClickToExpand.builder();

            CustomCardExpand cce = new CustomCardExpand(this);
            CustomCard card = new CustomCard(this);
            card.setShadow(false);
            card.addCardExpand(cce);
            card.setViewToClickToExpand(viewToClickToExpand); // <-- should make it click to expand,works on a single card,but not in the Recycler 
            c.setCard(card);
            cards.add(card);
        }
        CardArrayRecyclerViewAdapter mCardArrayAdapter = new CardArrayRecyclerViewAdapter(this, cards);
        //Staggered grid view
        CardRecyclerView mRecyclerView = (CardRecyclerView) findViewById(R.id.carddemo_recyclerview);
        mRecyclerView.setHasFixedSize(false);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        //Set the empty view
        if (mRecyclerView != null) {
            mRecyclerView.setAdapter(mCardArrayAdapter);
        }

Well i tried whatever , i want to be able to click on the card see animation of expansion and collapse on click again.How to achieve this , also i intend to have button in the "Expand" area which will trigger dialogue/new fragment and i will need to extract the info from the card into it , so i need to know which card it is in the list? Thanks in advance.

UPDATE:  Moved the setViewToClickToExpan(viewToClickToExpand); to the CustomCard class in the setupInnerViewElements(ViewGroup parent, View view) method and now it is working all along.In the loop adding card i use card.setId(String.valueOf(i));

In the CustomCardExpand , where i define the onClickListener for the button i call getParent().getId() to retrieve the ID of the card.

Hope it's gonna help someone , cheers !

**Comment by its-felipe-almeida** [comment]
how did you solved it?

**Comment by Dokuzov** [comment]
I really forgot, it was back in the days when i began programming in general, and it's likely i misused something.Anyway this is a code chunk i have left which seems to be working in the end.

```

   card = new CustomCard(context);
                    card.setId("" + repeatedList.get(i).getPayment().getId());
                    card.setShadow(true); // setting this false will remove the space between card and expand menu 
                    card.setViewToClickToExpand(ViewToClickToExpand
                            .builder()
                            .setupCardElement(ViewToClickToExpand.CardElementUI.CARD));
                    card.addCardExpand(cardExpand);
                    card.setPayment(repeatedList.get(i).getPayment());
                    cards.add(card);
```
