### ISSUE TITLE
cardslib:   Files not found

### ISSUE THREAD

**Issue by chittivenkat143** [gabrielemariotti/cardslib#505]
Hello Gabrielemariotti, 
Thanks for this CardView Expand article, but the examples which you mention in "Cards Library: Expand" are not found. 
1) CardExpandFragment.
2) ExpandPicassoFragment
3) ListExpandCardFragment.

Please link those files and help me to understand

**Comment by gabrielemariotti** [comment]
These files are simple Fragments used in the demo source. 
They are not part of the library
