### ISSUE TITLE
Is there a way to center the text horizontally in the header textview?

### ISSUE THREAD

**Issue by RedEagle07** [gabrielemariotti/cardslib#509]
How can I center the text horizontally inside my header? Actually the header ends up on using the wrap_content width instead of fill_parent for somereason.. any idea how to override this?

**Comment by Neuron64** [comment]
android:gravity="center"
or
 .setGravity(Gravity.CENTER);

**Comment by RedEagle07** [comment]
Not working, the problem I think is the textview wraps_content despite having its width as match_parent
