### ISSUE TITLE
Card.setTitle to support HTML tags

### ISSUE THREAD

**Issue by PcNy** [gabrielemariotti/cardslib#66]
This is just my suggestion. I found that common android TextView can apply HTML tags for flexibility of text formatting (like I found here http://stackoverflow.com/questions/7221930/change-text-color-of-one-word-in-a-textview).

It could be great if we can do the same with Card.setTitle function.

Sincerely,
PcNy

**Comment by andrewhlleung** [comment]
example

      card = new Card(getBaseContext());
      card.setTitle(Html.fromHtml("<font color='#EE0000'>red</font><div style='color:#ee1b2e;'>OK Red</div><h1>H1</h1><h2>H2</h2>").toString());
      header = new CardHeader(getBaseContext());
      header.setTitle(Html.fromHtml("<font color='#EE0000'>red</font><div style='color:#ee1b2e;'>OK Red</div><h1>H1</h1><h2>H2</h2>").toString());
      card.addCardHeader(header);
      cards.add(card);

h1,h2, div, font ok.
no color, only black color font display.

**Comment by andrewhlleung** [comment]
thx,
i can upate text color now.
how can I use hyperlink tag. <a href='http://www.google.com'>Test</a> <--- like that.
on click this link in my card content. no action.
